POST /api/user/register HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "username": "student_user",
  "password": "password123!",
  "code": ""  
}

###
POST /api/user/register HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "username": "professor_user",
  "password": "securePass123!",
  "code": "PROFESSOR1234"  
}
